name: app-build-action-dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  build-mac-ios-android:
    runs-on: ubuntu-latest

    

    steps:
      #签出代码
      - uses: actions/checkout@v3
        with:
          ref: master

      #设置JAVA环境
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      #设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'
          cache: true 

      #更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      #打包APK
      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi

      #上传Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
